controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_veterinarian_dashboard:
    path: /veterinarian/dashboard
    controller: App\Controller\VeterinarianController::dashboard
    requirements:
        _role: ROLE_VETERINARIAN

app_employee_dashboard:
    path: /employee/dashboard
    controller: App\Controller\employeeController::dashboard
    requirements:
        _role: ROLE_EMPLOYEE

app_vet_report_list:
    path: vet/report/list
    controller: App\Controller\VetReportController::list
    requirements:
        _role: ROLE_ADMIN
